# Лабораторная работа №1 "Работа с библиотекой NumPy"

 1. Импортируйте NumPy as np

In [1]:
import numpy as np

2. Создайте массив из 10 нулей

In [8]:
zeros_list = [0] * 10
print(zeros_list)

zeros_array = np.zeros(10)
print(zeros_array)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Создайте массив из 10 единиц

In [9]:
ones_list = [1] * 10
print(ones_list)

ones_array = np.ones(10)
print(ones_array)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


4. Создайте массив из 10 пятёрок

In [10]:
fives_list = [5] * 10
print(fives_list)

fives_array = np.full(10, 5)
print(fives_array)

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
[5 5 5 5 5 5 5 5 5 5]


5. Создайте массив целых чисел от 10 до 50 включительно

In [11]:
numbers_list = list(range(10, 51))  # 51 не включается, поэтому используем 51
print(numbers_list)

numbers_array = np.arange(10, 51)  # 51 не включается, поэтому используем 51
print(numbers_array)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


6. Создайте массив всех чётных чисел от 10 до 50 включительно

In [12]:
even_numbers_list = list(range(10, 51, 2))  # Шаг 2 для получения четных чисел
print(even_numbers_list)

even_numbers_array = np.arange(10, 51, 2)  # Шаг 2 для получения четных чисел
print(even_numbers_array)

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


7. Создайте матрицу 3x3 со значениями от 0 до 8 включительно

In [13]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


8. Создайте единичную матрицу размером 3x3

In [14]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


9. С помощью NumPy сгенерируйте случайное число в диапазоне от 0 до 1

In [15]:
random_number = np.random.rand()
print(random_number)

0.06842042476420429


10. С помощью NumPy сгенерируйте массив из 25 случайных чисел, выбранных из стандартного нормального распределения

In [16]:
random_array = np.random.randn(25)
print(random_array)

[ 0.24574093  0.92153724 -1.37228093 -1.02361538  0.5264797  -0.06080661
  1.59381365  1.69958966  0.0494081  -0.54504093 -1.1289948  -1.30784579
  1.59971681 -0.02865696 -0.04953329 -1.03013732  0.76301486 -1.16370896
 -1.96920106 -1.7725937  -1.67112632  0.88613488 -1.04346362  0.1719654
  1.18608622]


11. Создайте указанную  матрицу:
array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [17]:
specified_matrix = np.arange(0.01, 1.01, 0.01).reshape(10, 10)
print(specified_matrix)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


12. Создайте массив из 20 равноудалённых друг от друга точек между 0 и 1:

In [18]:
evenly_spaced_points = np.linspace(0, 1, 20)
print(evenly_spaced_points)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


13. Создайте матрицу mat размером 5*5 с числами от 1 по 25

In [19]:
mat = np.arange(1, 26).reshape(5, 5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


14. Напишите код, который на основе матрицы mat выведет указанную матрицу (подсказка - используйте индексацию).
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [20]:
sub_matrix_1 = mat[2:5, 1:5]  # строки 2-4, столбцы 1-4
print(sub_matrix_1)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


15. Напишите код, который на основе матрицы mat выведет указанную ниже матрицу:
20


In [21]:
number_20 = mat[3, 4]  # строка 3, столбец 4
print(number_20)

20


16. Напишите код, который на основе матрицы mat выведет указанную матрицу:
array([[ 2],
       [ 7],
       [12]])

In [28]:
sub_matrix_2 = mat[[0, 1, 2], [1]]  # строки 0, 1, 2, столбец 1
print(sub_matrix_2)

[ 2  7 12]


17. Напишите код, который на основе матрицы mat выведет указанную матрицу:
array([21, 22, 23, 24, 25])

In [23]:
row_5 = mat[4, 1:6]  # строка 4, столбцы 1-5
print(row_5)

[22 23 24 25]


18. Напишите код, который на основе матрицы mat выведет указанную матрицу:
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [24]:
sub_matrix_3 = mat[3:5, :]  # строки 3-4, все столбцы
print(sub_matrix_3)

[[16 17 18 19 20]
 [21 22 23 24 25]]


19. Найдите сумму всех чисел в матрице mat

In [25]:
total_sum = np.sum(mat)
print(total_sum)

325


20. Найдите среднеквадратичное отклонение значений в матрице mat

In [26]:
std_deviation = np.std(mat)
print(std_deviation)

7.211102550927978


21. Найдите сумму каждой из колонок в матрице mat

In [27]:
column_sum = np.sum(mat, axis=0)
print(column_sum)

[55 60 65 70 75]
